### ISSUE TITLE
subscribe_live_deal unused argument?

### ISSUE THREAD

**Issue by SebastianMoyano** [iqoptionapi/iqoptionapi#15]
I was checking the method but I don't seem to see where is buffersize used, when I use get_live_deal() it only goes up on size. So I find weird that the buffersize doesn't take effect at all.

`def subscribe_live_deal(self, name, active, _type, buffersize): active_id = OP_code.ACTIVES[active] self.api.Subscribe_Live_Deal(name, active_id, _type) """ self.api.live_deal_data[name][active][_type]=deque(list(),buffersize) while len(self.api.live_deal_data[name][active][_type])==0: self.api.Subscribe_Live_Deal(name,active_id,_type) time.sleep(1) """`
buffer size isn't used at all in the uncommented code. I tried using clear_live_deal() but I'm still experimenting because I'm not sure what it does.

I posted the issue on Lu-Yi-Hsun github but I'm not sure if it's going to be answered, the problem is that the get method only returns a bigger dictionary, that yes it contains up to date info, but it maintains the old and it looks like it doesn't have a limit.

**Comment by rrfaria** [comment]
It looks like a bug 
I will analyse it when I have free time .

**Comment by rrfaria** [comment]
since Iqoption has removed this option I'm closing this issue.
