### ISSUE TITLE
The API Has No Iq.get_balance_v2() Method

### ISSUE THREAD

**Issue by Qubits-Official** [iqoptionapi/iqoptionapi#17]
**Describe the bug**
According to the official documentation (https://iqoptionapi.github.io/iqoptionapi/en/account/account/)
![image](https://user-images.githubusercontent.com/50437107/86992309-cf653c80-c1d3-11ea-9c60-bd253d4ed3b5.png)

You should be able to use `Iq.get_balance_v2()`
It states that it provides more accuracy. (I have no idea what improvement/s it gives because I never have the chance to try it LOL)

**To Reproduce**
1. Use the code down below as a template.
`
from iqoptionapi.stable_api import IQ_Option
Iq = IQ_Option("change_email", "change_password"])
Iq.get_balance_v2()
`

**Expected behavior**
It should return a more accurate value of the account balance.

**Screenshots**
![image](https://user-images.githubusercontent.com/50437107/86992271-b5c3f500-c1d3-11ea-8a8d-3716e0565d8b.png)

**Additional context**
None

**Comment by rrfaria** [comment]
This code used is wrong

You must to use Iq.connect() after login
