### ISSUE TITLE
COPYTRADING IQ SOFTWARE

### ISSUE THREAD

**Issue by javierescobar10** [iqoptionapi/iqoptionapi#18]
Bom dia, eu estava observando em seu canal youtube, que você faz copytrading software no IQ Option. Vi que poderia valer cerca de 3.000, gostaria de falar sobre isso porque quero fazer um software com essas características. Estou esperando por sua resposta, sou da Colômbia, TE HABLÉ AL FACEBOOK

**Comment by rrfaria** [comment]
There is no more coytrade available on iq option. Iq Option has removed trading info from their site. and it is not available any more.

**Comment by javierescobar10** [comment]
https://youtu.be/fIB6iS4NYw0
