### ISSUE TITLE
There's no OP Code for GBPJPY-OTC instrument

### ISSUE THREAD

**Issue by bressanmarcos** [iqoptionapi/iqoptionapi#19]
**Describe the bug**
There's no OP Code for GBPJPY-OTC instrument

**To Reproduce**
import iqoptionapi.constants as OP_code
a = OP_code['GBPJPY-OTC']
--> KeyError

**Expected behavior**
We should get the code number referent to GBPJPY-OTC instrument

**Comment by rrfaria** [comment]
Was add some time ago.
