### ISSUE TITLE
Indicators SMA, Parabolic SAR, Bollinger Bands

### ISSUE THREAD

**Issue by KhanhPham2411** [iqoptionapi/iqoptionapi#25]
Anyone knows how to obtain indicators from the API? Or is there even indicators in the API in the first place?

**Comment by provezano** [comment]
Some of them you can replicate nicely with TA-Lib (https://mrjbq7.github.io/ta-lib/) or Pandas-TA(https://github.com/twopirllc/pandas-ta). Others, you can approximate to the values presented by IQ (eg. BBands).
