### ISSUE TITLE
error_place_digital_order in buy_digital_spot

### ISSUE THREAD

**Issue by wdragow** [iqoptionapi/iqoptionapi#40]
Hello, i am having this issue when i buy in digital:

>  {'code': 'error_place_digital_order', 'message': 'quotesApplication.ConsumeQuoteByTime: invalid instrument: doGBPNZD202103221915PT5.0MCSPT'}

How i fix this issue?

**To Reproduce**
On buy_digital_spot function

**Comment by rrfaria** [comment]
digital already fixed
