### ISSUE TITLE
instrument-quotes-generated should not be used to retrieve digital payout

### ISSUE THREAD

**Issue by LeonardoRick** [iqoptionapi/iqoptionapi#41]
**Describe the bug**
`instrument-quites-generated` should not be used to retrieve payout and use it return a wrong payout value for digital assets.

**To Reproduce**

**Expected behavior**
this part of the could should be updated:
Code that should be updated:
``` python
# ws/client.py line 298
elif message["name"]=="instrument-quotes-generated":
```

**Screenshots**

**Additional context**

**Comment by rrfaria** [comment]
Already fixed digital payout
