### ISSUE TITLE
Foreign Exchange Futures' API : buy_order() not working

### ISSUE THREAD

**Issue by lee-1980** [iqoptionapi/iqoptionapi#57]
Hello how are you? while I was using this function buy_order , I faced this issue.

- My environment to use buy_order function

                                instrument_id = "BTCUSD"
                                instrument_type = "crypto"
                                side = "buy"
                                if row[5] == 'BUY' or row[5] == 'buy' or row[5] == 'Buy':
                                    side = "buy"
                                elif row[5] == 'SELL' or row[5] == 'sell' or row[5] == 'Sell':
                                    side = 'sell'
                                amount = 0.23  
                                leverage = 3  
                                type = "market" 
                                limit_price = None
                                stop_price = None 
                                if row[9]:
                                    take_profit_kind = "percent" 
                                    take_profit_value = int(row[9].replace('%', '')) 
                                else:
                                    take_profit_kind = None
                                    take_profit_value = None
                                if row[10]:
                                    stop_lose_kind = "percent"  # input:None/"price"/"diff"/"percent"
                                    stop_lose_value = int(row[10].replace('%', ''))  # input:None/value(float/int)
                                else:
                                    stop_lose_kind = None
                                    stop_lose_value = None
                              
                                use_trail_stop = True  
                                auto_margin_call = False
                                use_token_for_commission = False  
                                check, order_id = self.API_connection.buy_order(instrument_type=instrument_type,
                                                                                instrument_id=instrument_id,
                                                                                side=side, amount=amount,
                                                                                leverage=leverage,
                                                                                type=type, limit_price=limit_price,
                                                                                stop_price=stop_price,
                                                                                stop_lose_value=stop_lose_value,
                                                                                stop_lose_kind=stop_lose_kind,
                                                                                take_profit_value=take_profit_value,
                                                                                take_profit_kind=take_profit_kind,
                                                                                use_trail_stop=use_trail_stop,
                                                                                auto_margin_call=auto_margin_call,
                                                                                use_token_for_commission=use_token_for_commission)

- When I try this code. I got this error lines without any message

File "C:\Users\manato\AppData\Local\Programs\Python\Python37\lib\site-packages\websocket\_app.py", line 343, in _callback
    callback(*args)
  File "C:\Users\manato\AppData\Local\Programs\Python\Python37\lib\site-packages\iqoptionapi\ws\client.py", line 243, in on_message
    self.api.buy_order_id = message["msg"]["id"]

- So I tried to track error myself , then I could get some message in websocket On_message function.
Message content is like this:

{'request_id': '', 'name': 'order-placed-temp', 'msg': {'message': 'Failed on command execution [4141] PlaceOrderException[Place order exception: ACCOUNT_TYPE_IS_MARGINAL]. Details: PlaceOrder(order=PlaceOrderV4(None,556658042,9,OrderInstrumentDirect(crypto,BTCUSD),buy,market,3,None,Some(0.23),None,None,None,None,Some(1.0),Some(percent),None,None,false,good_till_cancel,None,true,true), userId=117299705, wsTime=Some(2021-11-07T14:06:40.897Z))'}, 'status': 4141}

Can you please teach me what I did wrong or what is the reason? Thank you

**Comment by Cakricks** [comment]
I have same issue, how can i fixed?

_For_Forex_Stock_Commodities_Crypto_ETFs
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/websocket/_app.py", line 343, in _callback     callback(*args)                                       File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/iqoptionapi/ws/client.py", line 242, in on_message
    self.api.buy_order_id = message["msg"]["id"]

**Comment by lee-1980** [comment]
I figured it out myself, then  this is not related to any bugs of package.
I am sure you are using free account, then please try API with your real account verified.
Then API will work for Practise and Real accounts well.

**Comment by Cakricks** [comment]
> I figured it out myself, then this is not related to any bugs of package. I am sure you are using free account, then please try API with your real account verified. Then API will work for Practise and Real accounts well.
--------------------------------------------------
Yeeesss it is!!! THANK YOU!!

**Comment by lee-1980** [comment]
> > I figured it out myself, then this is not related to any bugs of package. I am sure you are using free account, then please try API with your real account verified. Then API will work for Practise and Real accounts well.
> 
> Yeeesss it is!!! THANK YOU!!

My pleasure, However , Can you help me another issue?

**Comment by Cakricks** [comment]
Yes sure

**Comment by tiagomakoto** [comment]
Same happened here:
File "C:\Users\tiago\anaconda3\lib\site-packages\websocket\_app.py", line 343, in _callback
    callback(*args)
  File "C:\Users\tiago\anaconda3\lib\site-packages\iqoptionapi\ws\client.py", line 139, in on_message
    order_placed_temp(self.api, message)
  File "C:\Users\tiago\anaconda3\lib\site-packages\iqoptionapi\ws\received\order_placed_temp.py", line 5, in order_placed_temp
    api.buy_order_id = message["msg"]["id"]
    
    However I do have a confirmed account. Demo only, though...

**Comment by DilshanIRU** [comment]
Yeah same error for me too. Almost completely similar to [tiagomakoto]'s one.
I also having a verified account.

Any idea about this? Appreciate your time.

**Comment by Mukasa-Joshua1** [comment]
> I figured it out myself, then this is not related to any bugs of package. I am sure you are using free account, then please try API with your real account verified. Then API will work for Practise and Real accounts well.

I am using verified account. Only on the practice account but I am still getting the same error.

**Comment by pankakj8710** [comment]
I looked into this and I think the IQ option has updated a lot of things, like now when sending websocket request we also need to include a lot of things 
```json
 {
        "category": "button_pressed",
        "name": "traderoom_deal-call",
        "uuid": "***",
        "active_session_uuid": "***",
        "connection_hash": "***",
        "value": 102.40900000000004,
        "user_id": 123456789,
        "group_id": 123,
        "platform_id": 9,
        "app_version": "2697.4.4127.release",
        "device_id": "***",
        "sync_time": 1669030015615,
        "client_time": 1669030015207,
        "parameters": {
            "asset_id": "1",
            "balance_type": "4",
            "instrument_type": "marginal-forex",
            "leverage_value": "500",
            "margin": "102.40900000000003",
            "market_price": "1.02406",
            "order_type": "market",
            "pip_value": "5.000000000000002",
            "quantity": "0.5",
            "single-click": "1"
        }
    },
```

I can figure out what to do with most of them but I don't know how to get `uuid`, `active_session_uuid`, `connection_hash`, `device_id`. also I checked there is no `instrument_id` , `stop_loss`, or `take_profit` If someone knows please let me know.

**Comment by thiago95macedo** [comment]
Hello,

I am facing a problem using iqoptionapi. I received the following error message:

{‘message’: ‘Failure in executing command [4141] PlaceOrderException[Exception when placing order: ACCOUNT_TYPE_IS_MARGINAL]. Details: PlaceOrder(order=PlaceOrderV4(None,577336469,9,OrderInstrumentDirect(forex,AUDJPY),sell,market,10,None,Some(2.0),None,None,Some(95.0),Some(percent),Some(50.0),None,None,None,false,good_till_cancel,None,false,true), userId=121389099, wsTime=Some(2023-12-22T06:11:01.600Z))’} Key ‘id’ not found in ‘message[msg]’

Apparently, the problem is related to the account type (ACCOUNT_TYPE_IS_MARGINAL). My account is already verified as a real account, but I am still facing this error.

Could someone help me understand what is happening and how I can solve this? I appreciate it in advance!

**Comment by CassioGirard** [comment]
I have the same problem, when using the function it gets stuck in the loop waiting to receive the ID. In line with stable_api: 
        while self.api.buy_order_id == None:
            Pass

**Comment by thiago95macedo** [comment]
https://github.com/thiago95macedo/iqoptionapi
