### ISSUE TITLE
Unresolved attribute reference 'set_max_reconnect' for class 'IQ_Option' 

### ISSUE THREAD

**Issue by dylotrons** [iqoptionapi/iqoptionapi#58]
Unresolved attribute reference 'set_max_reconnect' for class 'IQ_Option' 

The class does not have a function or attribute called "set_max_reconnect".

![image](https://user-images.githubusercontent.com/46464159/142732158-b43def60-7144-4ac0-a293-2525fbd46df4.png)

Note:
I have a lot of problems with reconnections. After a long period, the thread responsible for the reconnection crashes when the connection drops and it is necessary to call the api.connect() method.

**Comment by TheHolsback** [comment]
essa função foi retirada, na própria função connect vc pode definir o numero máximo de reconecções

this function is no longer working, in the function connect you can set max reconnections
