### ISSUE TITLE
check_win_v2 não funciona

### ISSUE THREAD

**Issue by jperim** [iqoptionapi/iqoptionapi#6]
post do Luiz que está funcionando, seria:

	# Function by kkagill ( https://github.com/Lu-Yi-Hsun/iqoptionapi/issues/196 | https://github.com/kkagill )
	# Function only work with Options!
    def check_win_v4(self, id_number):
        while True:
            try:
               if self.api.socket_option_closed[id_number] != None:
                   break
            except:
               pass
        x = self.api.socket_option_closed[id_number]
        return x['msg']['win'],(0 if x['msg']['win'] == 'equal' else float(x['msg']['sum']) * -1 if x['msg']['win'] == 'loose' else float(x['msg']['win_amount']) - float(x['msg']['sum']))

    # Function by Adenilson ( https://t.me/CardosoSlv )
	# Function only work with Options!
    def check_win_v3(self, id_number):
	       while True:
		          result = self.get_optioninfo_v2(10)
		          if result['msg']['closed_options'][0]['id'][0] == id_number and result['msg']['closed_options'][0]['id'][0] != None:			
			             return result['msg']['closed_options'][0]['win'],(result['msg']['closed_options'][0]['win_amount']-result['msg']['closed_options'][0]['amount'] if result['msg']['closed_options'][0]['win'] != 'equal' else 0)
			             break
		          time.sleep(1)

**Comment by jperim** [comment]
tb tive q mexer:

ws\chanels\api_game_betinfo.py

`import datetime
import time
from iqoptionapi.ws.chanels.base import Base
import logging
class Game_betinfo(Base):
    name = "api_game_betinfo"
    def __call__(self, id_number_list):
        data = {"currency": "USD"}
        if type(id_number_list) is list:
            for idx, val in enumerate(id_number_list):
                data["id["+str(idx)+"]"]=int(val)
        elif type(id_number_list) is tuple:
            data["id[0]"]=int(id_number_list[1])
        elif id_number_list is None:
            logging.error('**error** Game_betinfo can not input None type,please input buy id')
        else :
              data["id[0]"]=int(id_number_list)   
        self.send_websocket_request(self.name, data)`

**Comment by jperim** [comment]
client.py
na procedeure => def on_message(self, message):
adicionei:

`elif message["name"] == "socket-option-closed":
            id=message["msg"]["id"]
            self.api.socket_option_closed[id]=message`

**Comment by jperim** [comment]
api.py

class IQOptionAPI(object):

adicionei:
`socket_option_closed={}`

**Comment by ktamark** [comment]
Error en client.py

> client.py
> na procedeure => def on_message(self, message):
> adicionei:
> 
> `elif message["name"] == "socket-option-closed": id=message["msg"]["id"] self.api.socket_option_closed[id]=message`

Error :/
can you paste the entire fragment?

**Comment by rrfaria** [comment]
o @WeslleyJackson corrigido com codigo que o luiz fez ta usando check_win_v4 ou check_win_v3
