### ISSUE TITLE
iq.check_win not working

### ISSUE THREAD

**Issue by JoseFuentes-Coding** [iqoptionapi/iqoptionapi#77]
I am using the command 'Iq.check_win(id)' 'Iq.check_win_v2(id,3)' 'Iq.check_win_v3(id)' trying to get the result of a binary option trade and the program get stuck at this point

Iq=IQ_Option("joseg.fuentes001@gmail.com","Sor1970**")
Iq.connect()#connect to iqoption
print(Iq.check_connect())
#print(Iq.get_all_ACTIVES_OPCODE())
print('\n\n\n\n')
'''
ACTIVES="EURUSD-OTC"
duration=1#minuto 1 or 5
amount=1
action="call"#put
polling_time = 1
check,id=(Iq.buy_digital_spot(ACTIVES,amount,action,duration))'''
Money=1
ACTIVES="EURUSD-OTC"
ACTION="call"#or "put"
expirations_mode=1

d = Iq.get_all_profit()
print(d['EURUSD-OTC']['turbo'])
print(d['EURUSD-OTC']['binary'])

check,id=Iq.buy(Money,ACTIVES,ACTION,expirations_mode)
print('la id es: ' + str(id))
if check:
    print("!buy!")
else:
    print("buy fail")
if id !="error":
    while True:
        print('comprobando...')
        print('Primer chequeo')
        #print(Iq.check_win(id))
        print('Segundo chequeo')
        #print(Iq.check_win_v2(id,3))
        print('Tercer chequeo')
        print(Iq.check_win_v3(id))
![Anotación 2022-11-12 120457](https://user-images.githubusercontent.com/63337315/201483101-2e849f99-5425-4030-a68f-6e39e6ad88a9.jpg)

**Comment by ghost** [comment]
did you try with...
`res, profit = Iq.check_win_v4(id)`

**Comment by fromagge** [comment]
> `res, profit = Iq.check_win_v4(id)`

Worked, thanks!
