### ISSUE TITLE
HELP - Cannot login

### ISSUE THREAD

**Issue by maeltwosinggit** [iqoptionapi/iqoptionapi#92]
Thank you in advance for helping me!

I tried below code but result is check value is false

from iqoptionapi.stable_api import IQ_Option
import logging

logging.basicConfig(level=logging.DEBUG,format='%(asctime)s %(message)s')
Iq=IQ_Option("example@gmail.com","examplepassword123")
check, reason=Iq.connect()#connect to iqoption
print(check, reason)

here is the print(check) and print(reason) result:

check - False
reason - {"code":"verify","method":"push","token":"1-R1TtmSKvc5gv0iyYvIazI94SlcnhrWjMULhCwFexxirnzB2qcSQ1wceTDRyqHFn89Pifx6HAGN85hUAtaEAgI2j0wdBADShW5R9xPGlMjAAxZHXEHJRCh6WuZRYIqVOFUUCT0Qzex0JF4Jk6UghmBjiHhrSV8tbywQjRC5hEzjTw1mn_OyPRSOlw73Gi8p2SlbyEUZKrpeuNIgvwbN-Q"}

**Comment by maeltwosinggit** [comment]
its okay, solved it by turning off all 2-step verification.

Out of curiosity, how can we let the code pass through the 2-step verification?

**Comment by luckyscooby** [comment]
> its okay, solved it by turning off all 2-step verification.
> 
> Out of curiosity, how can we let the code pass through the 2-step verification?

https://github.com/iqoptionapi/iqoptionapi#como-realizar-login-com-2-fatores
