### ISSUE TITLE
CONSTANT.PY problem with new assets  us30-otc us100-otc  us500 otc ,problemas con nuevos pares disponibles 

### ISSUE THREAD

**Issue by mlhugueno** [iqoptionapi/iqoptionapi#97]
where are can search index for tis value, i need update for this new par
donde puedo encontrar los indices para los nuevos pares anexados a iq como son los us30 , ya trate de buscarlos por html pero no he encontrado nada

**Comment by wujileee** [comment]
I was having the same issue, so I had to modify the source code in stableapi.py located at C:\Users'user'\AppData\Local\Programs\Python'pythonversion'\Lib\site-packages\iqoptionapi on Windows.
```
def __get_binary_open(self):
        # for turbo and binary pairs
        binary_data = self.get_all_init_v2()
        binary_list = ["binary", "turbo"]
        if binary_data:
            for option in binary_list:
                if option in binary_data:
                    for actives_id in binary_data[option]["actives"]:
                        active = binary_data[option]["actives"][actives_id]
                        name = str(active["name"]).split(".")[1]
                        if active["enabled"] == True:
                            if active["is_suspended"] == True:
                                self.OPEN_TIME[option][name]["open"] = False
                            else:
                                self.OPEN_TIME[option][name]["open"] = True
                        else:
                            self.OPEN_TIME[option][name]["open"] = active["enabled"]
        
        # update binary actives opcode       
        for dirr in ["binary", "turbo"]:
            actives = binary_data[dirr]["actives"]
            for i, details in actives.items():
                name_part = details["name"].split(".")[1]
                OP_code.ACTIVES[name_part] = int(i) 
```


 ```
def __get_digital_open(self):
        # for digital options
        digital_data = self.get_digital_underlying_list_data()["underlying"]
        
        for digital in digital_data:
            name = digital["underlying"]
            schedule = digital["schedule"]
            self.OPEN_TIME["digital"][name]["open"] = False
            for schedule_time in schedule:
                start = schedule_time["open"]
                end = schedule_time["close"]
                if start < time.time() < end:
                    self.OPEN_TIME["digital"][name]["open"] = True
         
        # update digital actives opcode
        for item in digital_data:
            underlying_nome = item['underlying']
            active_id_valor = item['active_id']
            OP_code.ACTIVES[underlying_nome] = active_id_valor

```
``` 
def get_all_open_time(self):
        # all pairs openned
        self.OPEN_TIME = nested_dict(3, dict)
        
        binary = threading.Thread(target=self.__get_binary_open)
        digital = threading.Thread(target=self.__get_digital_open)
        
        #other = threading.Thread(target=self.__get_other_open)

        binary.start(), digital.start()#, other.start()
        binary.join(), digital.join()#, other.join()
        
        # ordenate updated actives opcode
        OP_code.ACTIVES = dict(sorted(OP_code.ACTIVES.items(), key=operator.itemgetter(1)))
        
        return self.OPEN_TIME
``` 

Locate these functions and replace them with the ones I sent you. Every time you call the function get_all_open_time(), the opcode asset list will update, and the new charts will be displayed. You always have to call this function when running your script to update the opcode. (Note: I turned off the function that retrieves assets for trading/forex to save time when executing the command, but if you want to revert, just remove the #'s)

I always use get_all_open_time() to fetch the pairs and create a list of the open pairs.
```
# Função para atualizar a lista de ativos abertos
def atualizar_lista_ativos_abertos():
    global ativos_digitais_abertos, API

    print(f"Capturando os ativos...")
    ALL_Asset = API.get_all_open_time()
    
    print(f"Verificando ativos abertos...")
    ativos_digitais_abertos = [ativo for ativo, info in ALL_Asset["digital"].items() if info["open"]]
    
    print(f"Abrindo ativos...")
    for ativo in ativos_digitais_abertos:
        API.stop_candles_stream(ativo, expiracao_segundos)
        API.start_candles_stream(ativo, expiracao_segundos, periodo_sma)
        
    print(f"Ativos atualizados...")
```

**Comment by wujileee** [comment]
If you want to know the opcode number of a particular asset, after making the changes in the source code, you can call the function get_all_open_time() and then print the function get_all_ACTIVES_OPCODE()

```
from iqoptionapi.stable_api import IQ_Option
logging.basicConfig(level=logging.ERROR, format='%(asctime)s %(message)s')
API = IQ_Option('email', 'senha')
API.connect()
if API.check_connect():
    print('Conectado com sucesso!')
else:
    print('Erro ao conectar')
    exit()

actives = API.get_all_open_time()
print(API.get_all_ACTIVES_OPCODE())
```

**Comment by mlhugueno** [comment]
Thank you very much, I appreciate the answers and I already put the code to work! thanks again

**Comment by mlhugueno** [comment]
""
"Module for IQ Option API constants."
""#~~~need to update~~~
ACTIVES = {
	"EURUSD": 1,
	"EURGBP": 2,
	"GBPJPY": 3,
	"EURJPY": 4,
	"GBPUSD": 5,
	"USDJPY": 6,
	"AUDCAD": 7,
	"NZDUSD": 8,
	"USDRUB": 10,
	"AMAZON": 31,
	"APPLE": 32,
	"BAIDU": 33,
	"CISCO": 34,
	"FACEBOOK": 35,
	"GOOGLE": 36,
	"INTEL": 37,
	"MSFT": 38,
	"YAHOO": 40,
	"AIG": 41,
	"CITI": 45,
	"COKE": 46,
	"GE": 48,
	"GM": 49,
	"GS": 50,
	"JPM": 51,
	"MCDON": 52,
	"MORSTAN": 53,
	"NIKE": 54,
	"USDCHF": 72,
	"XAUUSD": 74,
	"XAGUSD": 75,
	"EURUSD-OTC": 76,
	"EURGBP-OTC": 77,
	"USDCHF-OTC": 78,
	"EURJPY-OTC": 79,
	"NZDUSD-OTC": 80,
	"GBPUSD-OTC": 81,
	"GBPJPY-OTC": 84,
	"USDJPY-OTC": 85,
	"AUDCAD-OTC": 86,
	"ALIBABA": 87,
	"YANDEX": 95,
	"AUDUSD": 99,
	"USDCAD": 100,
	"AUDJPY": 101,
	"GBPCAD": 102,
	"GBPCHF": 103,
	"GBPAUD": 104,
	"EURCAD": 105,
	"CHFJPY": 106,
	"CADCHF": 107,
	"EURAUD": 108,
	"TWITTER": 113,
	"FERRARI": 133,
	"TESLA": 167,
	"USDNOK": 168,
	"EURNZD": 212,
	"USDSEK": 219,
	"USDTRY": 220,
	"MMM:US": 252,
	"ABT:US": 253,
	"ABBV:US": 254,
	"ACN:US": 255,
	"ATVI:US": 256,
	"ADBE:US": 258,
	"AAP:US": 259,
	"AA:US": 269,
	"AGN:US": 272,
	"MO:US": 278,
	"AMGN:US": 290,
	"T:US": 303,
	"ADSK:US": 304,
	"BAC:US": 313,
	"BBY:US": 320,
	"BA:US": 324,
	"BMY:US": 328,
	"CAT:US": 338,
	"CTL:US": 344,
	"CVX:US": 349,
	"CTAS:US": 356,
	"CTXS:US": 360,
	"CL:US": 365,
	"CMCSA:US": 366,
	"CXO:US": 369,
	"COP:US": 370,
	"ED:US": 371,
	"COST:US": 374,
	"CVS:US": 379,
	"DHI:US": 380,
	"DHR:US": 381,
	"DRI:US": 382,
	"DVA:US": 383,
	"DAL:US": 386,
	"DVN:US": 388,
	"DO:US": 389,
	"DLR:US": 390,
	"DFS:US": 391,
	"DISCA:US": 392,
	"DOV:US": 397,
	"DTE:US": 400,
	"DNB:US": 403,
	"ETFC:US": 404,
	"EMN:US": 405,
	"EBAY:US": 407,
	"ECL:US": 408,
	"EIX:US": 409,
	"EMR:US": 413,
	"ETR:US": 415,
	"EQT:US": 417,
	"EFX:US": 418,
	"EQR:US": 420,
	"ESS:US": 421,
	"EXPD:US": 426,
	"EXR:US": 428,
	"XOM:US": 429,
	"FFIV:US": 430,
	"FAST:US": 432,
	"FRT:US": 433,
	"FDX:US": 434,
	"FIS:US": 435,
	"FITB:US": 436,
	"FSLR:US": 437,
	"FE:US": 438,
	"FISV:US": 439,
	"FLS:US": 441,
	"FMC:US": 443,
	"FBHS:US": 448,
	"FCX:US": 450,
	"FTR:US": 451,
	"GILD:US": 460,
	"HAS:US": 471,
	"HON:US": 480,
	"IBM:US": 491,
	"KHC:US": 513,
	"LMT:US": 528,
	"MA:US": 542,
	"MDT:US": 548,
	"MU:US": 553,
	"NFLX:US": 569,
	"NEE:US": 575,
	"NVDA:US": 586,
	"PYPL:US": 597,
	"PFE:US": 603,
	"PM:US": 605,
	"PG:US": 617,
	"QCOM:US": 626,
	"DGX:US": 628,
	"RTN:US": 630,
	"CRM:US": 645,
	"SLB:US": 647,
	"SBUX:US": 666,
	"SYK:US": 670,
	"DIS:US": 689,
	"TWX:US": 692,
	"VZ:US": 723,
	"V:US": 726,
	"WMT:US": 729,
	"WBA:US": 730,
	"WFC:US": 733,
	"SNAP": 756,
	"DUBAI": 757,
	"TA25": 758,
	"AMD": 760,
	"ALGN": 761,
	"ANSS": 762,
	"DRE": 772,
	"IDXX": 775,
	"RMD": 781,
	"SU": 783,
	"TFX": 784,
	"TMUS": 785,
	"QQQ": 796,
	"SPY": 808,
	"BTCUSD": 816,
	"XRPUSD": 817,
	"ETHUSD": 818,
	"LTCUSD": 819,
	"DSHUSD": 821,
	"BCHUSD": 824,
	"OMGUSD": 825,
	"ZECUSD": 826,
	"ETCUSD": 829,
	"BTCUSD-L": 830,
	"ETHUSD-L": 831,
	"LTCUSD-L": 834,
	"BCHUSD-L": 836,
	"BTGUSD": 837,
	"QTMUSD": 845,
	"XLMUSD": 847,
	"TRXUSD": 858,
	"EOSUSD": 864,
	"USDINR": 865,
	"USDPLN": 866,
	"USDBRL": 867,
	"USDZAR": 868,
	"DBX": 889,
	"SPOT": 891,
	"USDSGD": 892,
	"USDHKD": 893,
	"LLOYL-CHIX": 894,
	"VODL-CHIX": 895,
	"BARCL-CHIX": 896,
	"TSCOL-CHIX": 897,
	"BPL-CHIX": 898,
	"HSBAL-CHIX": 899,
	"RBSL-CHIX": 900,
	"BLTL-CHIX": 901,
	"MRWL-CHIX": 902,
	"STANL-CHIX": 903,
	"RRL-CHIX": 904,
	"MKSL-CHIX": 905,
	"BATSL-CHIX": 906,
	"ULVRL-CHIX": 908,
	"EZJL-CHIX": 909,
	"ADSD-CHIX": 910,
	"ALVD-CHIX": 911,
	"BAYND-CHIX": 912,
	"BMWD-CHIX": 913,
	"CBKD-CHIX": 914,
	"COND-CHIX": 915,
	"DAID-CHIX": 916,
	"DBKD-CHIX": 917,
	"DPWD-CHIX": 919,
	"DTED-CHIX": 920,
	"EOAND-CHIX": 921,
	"MRKD-CHIX": 922,
	"SIED-CHIX": 923,
	"TKAD-CHIX": 924,
	"VOW3D-CHIX": 925,
	"ENELM-CHIX": 926,
	"ENIM-CHIX": 927,
	"PIRCM-CHIX": 929,
	"PSTM-CHIX": 930,
	"TITM-CHIX": 931,
	"UCGM-CHIX": 932,
	"CSGNZ-CHIX": 933,
	"NESNZ-CHIX": 934,
	"ROGZ-CHIX": 935,
	"UBSGZ-CHIX": 936,
	"SANE-CHIX": 937,
	"BBVAE-CHIX": 938,
	"TEFE-CHIX": 939,
	"AIRP-CHIX": 940,
	"HEIOA-CHIX": 941,
	"ORP-CHIX": 942,
	"AUDCHF": 943,
	"AUDNZD": 944,
	"CADJPY": 945,
	"EURCHF": 946,
	"GBPNZD": 947,
	"NZDCAD": 948,
	"NZDJPY": 949,
	"EURSEK": 950,
	"EURNOK": 951,
	"CHFSGD": 952,
	"EURSGD": 955,
	"USDMXN": 957,
	"JUVEM": 958,
	"ASRM": 959,
	"MANU": 966,
	"UKOUSD": 969,
	"XPTUSD": 970,
	"USOUSD": 971,
	"W1": 977,
	"AUDDKK": 983,
	"AUDMXN": 985,
	"AUDNOK": 986,
	"AUDSEK": 988,
	"AUDSGD": 989,
	"AUDTRY": 990,
	"CADMXN": 992,
	"CADNOK": 993,
	"CADPLN": 994,
	"CADTRY": 995,
	"CHFDKK": 996,
	"CHFNOK": 998,
	"CHFSEK": 1000,
	"CHFTRY": 1001,
	"DKKPLN": 1004,
	"DKKSGD": 1005,
	"EURDKK": 1007,
	"EURMXN": 1008,
	"EURTRY": 1010,
	"EURZAR": 1011,
	"GBPILS": 1013,
	"GBPMXN": 1014,
	"GBPNOK": 1015,
	"GBPPLN": 1016,
	"GBPSEK": 1017,
	"GBPSGD": 1018,
	"GBPTRY": 1019,
	"NOKDKK": 1023,
	"NOKJPY": 1024,
	"NOKSEK": 1025,
	"NZDDKK": 1026,
	"NZDMXN": 1027,
	"NZDNOK": 1028,
	"NZDSEK": 1030,
	"NZDSGD": 1031,
	"NZDTRY": 1032,
	"NZDZAR": 1033,
	"PLNSEK": 1036,
	"SEKDKK": 1037,
	"SEKJPY": 1038,
	"SGDJPY": 1041,
	"USDDKK": 1045,
	"NZDCHF": 1048,
	"GBPHUF": 1049,
	"USDCZK": 1050,
	"USDHUF": 1051,
	"CADSGD": 1054,
	"EURCZK": 1056,
	"EURHUF": 1057,
	"USDTHB": 1062,
	"IOTUSD-L": 1116,
	"XLMUSD-L": 1117,
	"NEOUSD-L": 1118,
	"ADAUSD-L": 1119,
	"XEMUSD-L": 1120,
	"XRPUSD-L": 1122,
	"EEM": 1203,
	"FXI": 1204,
	"IWM": 1205,
	"GDX": 1206,
	"XOP": 1209,
	"XLK": 1210,
	"XLE": 1211,
	"XLU": 1212,
	"IEMG": 1213,
	"XLY": 1214,
	"IYR": 1215,
	"SQQQ": 1216,
	"OIH": 1217,
	"SMH": 1218,
	"EWJ": 1219,
	"XLB": 1221,
	"DIA": 1222,
	"TLT": 1223,
	"SDS": 1224,
	"EWW": 1225,
	"XME": 1227,
	"QID": 1229,
	"AUS200": 1230,
	"FRANCE40": 1231,
	"GERMANY30": 1232,
	"HONGKONG50": 1233,
	"SPAIN35": 1234,
	"US30": 1235,
	"USNDAQ100": 1236,
	"JAPAN225": 1237,
	"USSPX500": 1239,
	"UK100": 1241,
	"TRXUSD-L": 1242,
	"EOSUSD-L": 1244,
	"BNBUSD-L": 1279,
	"ACB": 1288,
	"CGC": 1289,
	"CRON": 1290,
	"GWPH": 1291,
	"MJ": 1292,
	"TLRY": 1293,
	"BUD": 1294,
	"LYFT": 1313,
	"PINS": 1315,
	"ZM": 1316,
	"UBER": 1334,
	"MELI": 1335,
	"BYND": 1336,
	"BSVUSD-L": 1338,
	"ONTUSD-L": 1339,
	"ATOMUSD-L": 1340,
	"WORK": 1343,
	"FDJP": 1350,
	"CAN": 1351,
	"VIAC": 1352,
	"TFC": 1353,
	"USDXOF-OTC": 1379,
	"USDZAR-OTC": 1380,
	"USDSGD-OTC": 1381,
	"USDHKD-OTC": 1382,
	"USDINR-OTC": 1383,
	"DOGEUSD-L": 1406,
	"USSPX500:N": 1470,
	"USNDAQ100:N": 1471,
	"US30:N": 1472,
	"USDJPY-op": 1865,
	"GBPJPY-op": 1866,
	"GBPUSD-op": 1867,
	"AUDCAD-op": 1868,
	"AUDCHF-op": 1884,
	"CISCO-op": 1902,
	"CITI-op": 1903,
	"SNAP-op": 1904,
	"TESLA-op": 1905,
	"MCDON-op": 1906,
	"MORSTAN-op": 1907,
	"ALIBABA-op": 1908,
	"AMAZON-op": 1909,
	"APPLE-op": 1910,
	"BAIDU-op": 1911,
	"COKE-op": 1922,
	"MSFT-op": 1923,
	"NIKE-op": 1924,
	"FACEBOOK-op": 1925,
	"GOOGLE-op": 1926,
	"GS-op": 1927,
	"INTEL-op": 1928,
	"JPM-op": 1929,
	"AIG-op": 1930,
	"SP500-OTC": 1971,
	"USNDAQ100-OTC": 1972,
	"US30-OTC": 1973

}

**Comment by thiago95macedo** [comment]
"""
"Module for IQ Option API constants."
"""
#~~~need to update~~~
ACTIVES = {
    "EURUSD": 1,
    "EURGBP": 2,
    "GBPJPY": 3,
    "EURJPY": 4,
    "GBPUSD": 5,
    "USDJPY": 6,
    "AUDCAD": 7,
    "NZDUSD": 8,
    "USDRUB": 10,
    "AMAZON": 31,
    "APPLE": 32,
    "BAIDU": 33,
    "CISCO": 34,
    "FACEBOOK": 35,
    "GOOGLE": 36,
    "INTEL": 37,
    "MSFT": 38,
    "YAHOO": 40,
    "AIG": 41,
    "CITI": 45,
    "COKE": 46,
    "GE": 48,
    "GM": 49,
    "GS": 50,
    "JPM": 51,
    "MCDON": 52,
    "MORSTAN": 53,
    "NIKE": 54,
    "USDCHF": 72,
    "XAUUSD": 74,
    "XAGUSD": 75,
    "EURUSD-OTC": 76,
    "EURGBP-OTC": 77,
    "USDCHF-OTC": 78,
    "EURJPY-OTC": 79,
    "NZDUSD-OTC": 80,
    "GBPUSD-OTC": 81,
    "GBPJPY-OTC": 84,
    "USDJPY-OTC": 85,
    "AUDCAD-OTC": 86,
    "ALIBABA": 87,
    "YANDEX": 95,
    "AUDUSD": 99,
    "USDCAD": 100,
    "AUDJPY": 101,
    "GBPCAD": 102,
    "GBPCHF": 103,
    "GBPAUD": 104,
    "EURCAD": 105,
    "CHFJPY": 106,
    "CADCHF": 107,
    "EURAUD": 108,
    "TWITTER": 113,
    "FERRARI": 133,
    "TESLA": 167,
    "USDNOK": 168,
    "EURNZD": 212,
    "USDSEK": 219,
    "USDTRY": 220,
    "MMM:US": 252,
    "ABT:US": 253,
    "ABBV:US": 254,
    "ACN:US": 255,
    "ATVI:US": 256,
    "ADBE:US": 258,
    "AAP:US": 259,
    "AA:US": 269,
    "AGN:US": 272,
    "MO:US": 278,
    "AMGN:US": 290,
    "T:US": 303,
    "ADSK:US": 304,
    "BAC:US": 313,
    "BBY:US": 320,
    "BA:US": 324,
    "BMY:US": 328,
    "CAT:US": 338,
    "CTL:US": 344,
    "CVX:US": 349,
    "CTAS:US": 356,
    "CTXS:US": 360,
    "CL:US": 365,
    "CMCSA:US": 366,
    "CXO:US": 369,
    "COP:US": 370,
    "ED:US": 371,
    "COST:US": 374,
    "CVS:US": 379,
    "DHI:US": 380,
    "DHR:US": 381,
    "DRI:US": 382,
    "DVA:US": 383,
    "DAL:US": 386,
    "DVN:US": 388,
    "DO:US": 389,
    "DLR:US": 390,
    "DFS:US": 391,
    "DISCA:US": 392,
    "DOV:US": 397,
    "DTE:US": 400,
    "DNB:US": 403,
    "ETFC:US": 404,
    "EMN:US": 405,
    "EBAY:US": 407,
    "ECL:US": 408,
    "EIX:US": 409,
    "EMR:US": 413,
    "ETR:US": 415,
    "EQT:US": 417,
    "EFX:US": 418,
    "EQR:US": 420,
    "ESS:US": 421,
    "EXPD:US": 426,
    "EXR:US": 428,
    "XOM:US": 429,
    "FFIV:US": 430,
    "FAST:US": 432,
    "FRT:US": 433,
    "FDX:US": 434,
    "FIS:US": 435,
    "FITB:US": 436,
    "FSLR:US": 437,
    "FE:US": 438,
    "FISV:US": 439,
    "FLS:US": 441,
    "FMC:US": 443,
    "FBHS:US": 448,
    "FCX:US": 450,
    "FTR:US": 451,
    "GILD:US": 460,
    "HAS:US": 471,
    "HON:US": 480,
    "AMZNALIBABA-OTC": 2082,
    "TESLAFORD-OTC": 2087,
    "Yen_Index": 2063,
    "US100JP225-OTC": 2080,
    "EURGBP_GS": 2133,
    "NZDCAD-OTC": 2137,
    "GBPUSD-op": 1867,
    "RONINUSD-OTC": 2161,
    "NVDAAMD-OTC": 2084,
    "AUDUSD-op": 1870,
    "USDSGD-OTC": 1381,
    "SP35-OTC": 2044,
    "GBPAUD-OTC": 2116,
    "USDNOK-OTC": 2121,
    "STXUSD-OTC": 2166,
    "EURCHF-OTC": 2131,
    "IMXUSD-OTC": 2140,
    "ARBUSD-OTC": 2156,
    "US30-OTC": 1973,
    "CADCHF-OTC": 2119,
    "US500JP225-OTC": 2081,
    "GER30UK100-OTC": 2093,
    "EURUSD-op": 1861,
    "NZDCHF-OTC": 2202,
    "TESLA-OTC": 1936,
    "COKE-OTC": 2101,
    "DOTUSD-OTC": 2149,
    "GBPNZD-OTC": 2132,
    "METAGOOGLE-OTC": 2094,
    "CADJPY-OTC": 2136,
    "GBPJPY-op": 1866,
    "GOOGLEMSFT-OTC": 2085,
    "NFLXAMZN-OTC": 2090,
    "GALAUSD-OTC": 2147,
    "AUDNZD-OTC": 2130,
    "JP225-OTC": 2051,
    "SEIUSD-OTC": 2152,
    "ORDIUSD-OTC": 2158,
    "WIFUSD-OTC": 2144,
    "AMZNEBAY-OTC": 2083,
    "INTELIBM-OTC": 2089,
    "BONKUSD-OTC": 2142,
    "DOTUSD": 1381,
    "GRTUSD-OTC": 2165,
    "MSFT-OTC": 2099,
    "TONUSD-OTC": 2091,
    "AMAZON-OTC": 1935,
    "AUDJPY-op": 1869,
    "AUDJPY-OTC": 2113,
    "XAUXAG-OTC": 2086,
    "EOSUSD": 864,
    "INTEL-OTC": 2098,
    "APPLE-OTC": 1938,
    "USDCAD-OTC": 2112,
    "EURNZD-OTC": 2122,
    "FB-OTC": 1937,
    "XRPUSD-OTC": 2107,
    "TRUMPvsHARRIS-OTC": 2185,
    "ALIBABA-OTC": 2100,
    "MKRUSD-OTC": 2167,
    "AUDCHF-OTC": 2138,
    "TRUMPvsBIDEN-OTC": 2186,
}

**Comment by thiago95macedo** [comment]
import json
from iqoptionapi.stable_api import IQ_Option
from colorama import Fore

# Initialize Colorama to color the terminal output
def init_colorama():
    # The colorama library is used to color the terminal text, making error and info messages easier to spot.
    import colorama
    colorama.init(autoreset=True)

# Function to load the credentials from the config.json file
def load_configuration():
    try:
        # Opens the 'config.json' file and loads the configuration data, such as email and password for the IQ Option account.
        with open('config.json', 'r') as config_file:
            config = json.load(config_file)
        return config
    except Exception as e:
        # If there's an error loading the configuration file, it prints an error message.
        print(f"{Fore.RED}⚠️ Error loading the configuration file: {e}")
        return None

# Function to connect to the IQ Option API
def connect_to_api(config):
    # Retrieves the credentials (email and password) from the loaded configuration
    email = config.get("iqoption", {}).get("email")
    password = config.get("iqoption", {}).get("password")
    
    # Creates an IQ_Option instance with the credentials
    API = IQ_Option(email, password)
    
    # Attempts to connect to the API. If unsuccessful, prints an error message.
    if not API.connect():
        print(f"{Fore.RED}⚠️ Could not connect to the API. Please check your credentials.")
        return None
    
    return API

# Function to get the asset opcodes mapping
def get_assets_opcodes(API):
    try:
        # Calls the API function to get all available asset opcodes on the IQ Option platform
        opcodes = API.get_all_ACTIVES_OPCODE()
        
        # Checks if any opcodes were returned. If not, raises an error.
        if not opcodes:
            raise ValueError("No opcodes returned by the API.")

        # Creates a list of dictionaries, each containing the name of the asset and its respective opcode.
        assets_opcodes = [{"name": name, "opcode": opcode} for name, opcode in opcodes.items()]
        return assets_opcodes
    except Exception as e:
        # If there's an error obtaining the opcodes, prints an error message.
        print(f"{Fore.RED}⚠️ Error obtaining asset opcodes: {e}")
        return []

# Function to generate the constants.py file with assets and opcodes
def generate_constants(assets_opcodes):
    try:
        # Path to the constants.py file
        constants_path = r"dependencias\iqoptionapi\iqoptionapi\constants.py"
        
        # Opens the constants.py file for writing and overwrites any existing content
        with open(constants_path, "w") as f:
            # Writes a header in the constants.py file
            f.write('"""\n"Module for IQ Option API constants."\n"""\n')
            f.write('#~~~need to update~~~\n')
            f.write("ACTIVES = {\n")
            
            # For each asset and its opcode, writes it into the constants.py file
            for asset in assets_opcodes:
                f.write(f'    "{asset["name"]}": {asset["opcode"]},\n')
            
            f.write("}\n")
        
        # If the file is successfully updated, prints a success message in the terminal
        print(f"{Fore.GREEN}✅ 'constants.py' file successfully updated!")
    
    except Exception as e:
        # If there's an error writing to the file, prints an error message.
        print(f"{Fore.RED}⚠️ Error updating the 'constants.py' file: {e}")

# Main function
def main():
    # Initializes Colorama to color terminal output
    init_colorama()
    
    # Loads the configuration (email and password) from the 'config.json' file
    config = load_configuration()
    if not config:
        return

    # Connects to the API using the loaded credentials
    API = connect_to_api(config)
    if not API:
        return

    # Informs the user that the opcodes for all available assets are being fetched
    print(f"{Fore.YELLOW}🔍 Fetching opcodes for all available assets on the platform...\n")
    
    # Gets the opcodes of the assets
    assets_opcodes = get_assets_opcodes(API)
    
    if assets_opcodes:
        # If the opcodes are successfully obtained, it prints the name and opcode of each asset
        print(f"{Fore.GREEN}✅ Opcodes for the available assets ({len(assets_opcodes)} found):")
        for asset in assets_opcodes:
            print(f" - Name: {asset['name']}, Opcode: {asset['opcode']}")
        
        # Updates the constants.py file with the assets and opcodes obtained
        generate_constants(assets_opcodes)
    else:
        # If no opcodes were obtained, it prints an error message
        print(f"{Fore.RED}⚠️ Could not obtain asset opcodes.")

    # Informs the user that the program is running and can be stopped with Ctrl + C
    print(f"\n{Fore.CYAN}💡 Press Ctrl + C to exit the program.")
    while True:  # Keeps the terminal open
        pass

# Executes the program if this file is called directly
if __name__ == "__main__":
    main()
